name = "KitePodModels"
uuid = "9de5dc81-f971-414a-927b-652b2f41c539"
authors = ["Uwe Fechner <uwe.fechner.msc@gmail.com> and contributors"]
version = "0.1.2"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
DocStringExtensions = "0.8"
KiteUtils = "0.2.5, 0.2.6, 0.3.0, 0.3.1, 0.3"
Parameters = "0.12"
julia = "1.6, 1.7"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
