name = "KitePodModels"
uuid = "9de5dc81-f971-414a-927b-652b2f41c539"
authors = ["Uwe Fechner <uwe.fechner.msc@gmail.com> and contributors"]
version = "0.3.4"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
ControlPlots = "0.1.5"
LaTeXStrings = "1.3"
DocStringExtensions = "0.8, 0.9"
KiteUtils = "0.7.5"
Reexport = "1.2"
julia = "1.10"

[extras]
ControlPlots = "23c2ee80-7a9e-4350-b264-8e670f12517c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ControlPlots", "LaTeXStrings"]
