name = "KitePodModels"
uuid = "9de5dc81-f971-414a-927b-652b2f41c539"
authors = ["Uwe Fechner <uwe.fechner.msc@gmail.com> and contributors"]
version = "0.2.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DocStringExtensions = "0.8, 0.9"
KiteUtils = "0.4"
Reexport = "1.2"
julia = "1.6, 1.7, 1.8"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
