name = "KitePodSimulator"
uuid = "558fcde3-b420-4fcf-b6fa-fc874c7e75b7"
authors = ["Uwe Fechner <uwe.fechner.msc@gmail.com> and contributors"]
version = "0.1.0"

[deps]
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1.6, 1.7"
KiteUtils = "0.2.3"
Parameters = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

